#!/bin/bash

set -e

if [ "$1" != "configure" ]; then
	exit 0
fi

# Touch and set permisions on default log files on installation
update-rc.d lokahostcp defaults > /dev/null
invoke-rc.d lokahostcp start || true

# Adapt Port Listing in LOKAHOSTCP NGINX Backend
source /usr/local/lokahostcp/func/syshealth.sh # Load syshealth functions
syshealth_adapt_lokahostcp_nginx_listen_ports  # Adapt port listing
syshealth_adapt_nginx_resolver

# Run triggers only on updates
if [ ! -e "/usr/local/lokahostcp/data/users/" ]; then
	exit
fi

###############################################################
#                Initialize functions/variables               #
###############################################################

if [ -z "$LOKAHOSTCP" ]; then
	export LOKAHOSTCP='/usr/local/lokahostcp'
	PATH=$PATH:/usr/local/lokahostcp/bin
	export PATH
fi

# Check if preinstall hook exists
if [ -e "/etc/lokahostcp/hooks/nginx/pre_install.sh" ]; then
	/etc/lokahostcp/hooks/nginx/pre_install.sh
fi

# Load upgrade functions and variables
source /usr/local/lokahostcp/func/main.sh
source /usr/local/lokahostcp/func/upgrade.sh
source /usr/local/lokahostcp/conf/lokahostcp.conf
source /usr/local/lokahostcp/install/upgrade/upgrade.conf

# Reset backend port
if [ -n "$BACKEND_PORT" ]; then
	/usr/local/lokahostcp/bin/v-change-sys-port $BACKEND_PORT
fi

if [ -e "/etc/lokahostcp/hooks/nginx/post_install.sh" ]; then
	/etc/lokahostcp/hooks/nginx/post_install.sh
fi

# Restart lokahostcp service
if [ -f "/etc/init.d/lokahostcp" ]; then
	systemctl restart lokahostcp > /dev/null 2>&1
fi
