#!/bin/bash

set -e

if [ "$1" != "configure" ]; then
	exit 0
fi

# Run triggers below only on updates
if [ ! -e "/usr/local/lokahostcp/data/users/" ]; then
	exit
fi

# Check if preinstall hook exists
if [ -e "/etc/lokahostcp/hooks/php/pre_install.sh" ]; then
	/etc/lokahostcp/hooks/php/pre_install.sh
fi

###############################################################
#                Initialize functions/variables               #
###############################################################

if [ -z "$LOKAHOSTCP" ]; then
	export LOKAHOSTCP='/usr/local/lokahostcp'
	PATH=$PATH:/usr/local/lokahostcp/bin
	export PATH
fi

# Load upgrade functions and variables
source /usr/local/lokahostcp/func/main.sh
source /usr/local/lokahostcp/func/upgrade.sh
source /usr/local/lokahostcp/conf/lokahostcp.conf
source /usr/local/lokahostcp/install/upgrade/upgrade.conf

# Restart lokahostcp service
if [ -f "/etc/init.d/lokahostcp" ]; then
	systemctl restart lokahostcp > /dev/null 2>&1
fi

# Check if preinstall hook exists
if [ -e "/etc/lokahostcp/hooks/php/post_install.sh" ]; then
	/etc/lokahostcp/hooks/php/post_install.sh
fi
