#!/bin/bash

# Lokahost Control Panel upgrade script for target version 1.3.3

#######################################################################################
#######                      Place additional commands below.                   #######
#######################################################################################

# Check if keys folder exists and adjust permissions
if [ -d "$LOKAHOST/data/keys" ]; then
	echo '[ * ] Update permissions'
	chmod 750 "$LOKAHOST/data/keys"
	chown admin:root "$LOKAHOST/data/keys"
fi

if [[ ! -e /etc/lokahost/lokahost.conf ]]; then
	echo '[ * ] Create global Lokahost config'

	mkdir -p /etc/lokahost
	echo -e "# Do not edit this file, will get overwritten on next upgrade, use /etc/lokahost/local.conf instead\n\nexport LOKAHOST='/usr/local/lokahost'\n\n[[ -f /etc/lokahost/local.conf ]] && source /etc/lokahost/local.conf" > /etc/lokahost/lokahost.conf
fi
