name: Crowdin

on:
  workflow_dispatch:

jobs:
  update-pot:
    name: Update .pot file
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        if: github.repository == 'lokahostcp/lokahostcp'
      - name: crowdin action
        uses: crowdin/github-action@fdc55cdc519e86e32c22a07528d649277f1127f2 # v1
        if: github.repository == 'lokahostcp/lokahostcp'
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
