#!/bin/bash

set -e

if [ "$1" != "configure" ]; then
	exit 0
fi

# Run triggers below only on updates
if [ ! -e "/usr/local/lokahostcp/data/users/admin" ]; then
	exit
fi

###############################################################
#                Initialize functions/variables               #
###############################################################

if [ -z "$LOKAHOSTCP" ]; then
	export LOKAHOSTCP='/usr/local/lokahostcp'
	PATH=$PATH:/usr/local/lokahostcp/bin
	export PATH
fi

# Load upgrade functions and variables
source /usr/local/lokahostcp/func/main.sh
source /usr/local/lokahostcp/func/upgrade.sh
source /usr/local/lokahostcp/conf/lokahostcp.conf
source /usr/local/lokahostcp/install/upgrade/upgrade.conf

# Restart lokahostcp-web-terminal service if enabled
if [ -f "/etc/systemd/system/lokahostcp-web-terminal.service" ]; then
	systemctl daemon-reload > /dev/null 2>&1
	if systemctl is-enabled lokahostcp-web-terminal > /dev/null 2>&1; then
		systemctl restart lokahostcp-web-terminal
	fi
fi
